### ISSUE TITLE
power draw chart

### ISSUE THREAD

**Issue by Woking-34** [GameTechDev/asteroids_d3d12#1]
Could you please share how to query the power draw to presenet the power graph similar to the one that can be found in the demo screen?

https://software.intel.com/sites/default/files/managed/55/4a/DirectX-12-uses-less-than-half-the-CPU-power-when-compared-to-DirectX-11.jpg

**Comment by punkUser** [comment]
The best way is to use something like Intel Xtreme Tuning Utility or Power Gadget (https://software.intel.com/en-us/articles/intel-power-gadget-20). The latter I believe has an API for extracting power data that you can embed in other applications.

The specific overlay we used there is not something we are able to release publicly, but the data is the same that comes out of Power Gadget or XTU.
