### ISSUE TITLE
Missing Shader Header files.

### ISSUE THREAD

**Issue by cmartin99** [GameTechDev/asteroids_d3d12#2]
These files appear to be missing from the repo
# include "asteroid_vs.h"
# include "asteroid_ps.h"
# include "skybox_vs.h"
# include "skybox_ps.h"
# include "sprite_vs.h"
# include "sprite_ps.h"
# include "font_ps.h"

**Comment by punkUser** [comment]
Those should be generated by the build. See the "HLSL tool" for the associated shaders in MSVC.

**Comment by cmartin99** [comment]
That fixed it, many thanks.

btw I was able to render 200k asteriods @ 60 fps.

i7-4790 CPU
NVIDIA GeForce GTX 960
