### ISSUE TITLE
missing <cmath> in camera.cpp

### ISSUE THREAD

**Issue by bvanevery** [GameTechDev/asteroids_d3d12#4]
I'm on Windows 10.  I imported the .sln to Visual Studio 2019.  It did some automatic project conversions and let me use the most current SDK.  When building the solution I get the following errors:

1>C:\devel\asteroids_d3d12\src\camera.cpp(91,24): error C2039: 'sin': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vector(24): message : see declaration of 'std'
1>C:\devel\asteroids_d3d12\src\camera.cpp(91,46): error C2039: 'cos': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vector(24): message : see declaration of 'std'
1>C:\devel\asteroids_d3d12\src\camera.cpp(92,24): error C2039: 'cos': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vector(24): message : see declaration of 'std'
1>C:\devel\asteroids_d3d12\src\camera.cpp(93,24): error C2039: 'sin': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vector(24): message : see declaration of 'std'
1>C:\devel\asteroids_d3d12\src\camera.cpp(93,46): error C2039: 'sin': is not a member of 'std'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\vector(24): message : see declaration of 'std'

Adding
`#include <cmath>`
as the last header file, makes the problem go away.  Build succeeds and the demo runs.

On a completely different Windows 10 machine, using Visual Studio 2017, I didn't need this.  I don't know how clean that build environment is, or how many additional developer tools I've installed.

**Comment by JeffersonMontgomery-Intel** [comment]
Thank-you for the report!  Fix added to master.
